const { test, expect } = require('@playwright/test');
test('core ui', async ({ page }) => {
  const errors=[]; page.on('pageerror',e=>errors.push(String(e)));
  await page.goto('http://127.0.0.1:4173/index.html');
  await expect(page.locator('[data-app-version]')).toHaveText('v1.4.29');
  await page.locator('#topSettingsButton').click();
  await expect(page.locator('#settingsDialog')).toHaveJSProperty('open',true);
  await page.locator('#settingsDialog .dialog-close').click();
  await page.locator('#newChatButton').click();
  await expect(page.locator('#chatList .chat-item')).toHaveCount(2);
  await page.locator('#providerSelect').selectOption('openai');
  await expect(page.locator('#modelSelect option')).not.toHaveCount(0);
  await expect(page.locator('#modelSelect')).toHaveValue(/.+/);
  await expect(page.locator('#adoptIdeaButton')).toBeDisabled();
  await page.evaluate(()=>window.MCLExplicitModeV136.storeProposal('Neue Idee: bewegter Mittelteil, kontrastierende Begleitung.'));
  await expect(page.locator('#adoptIdeaButton')).toBeEnabled();
  await page.locator('#adoptIdeaButton').click();
  await expect(page.locator('#compositionIdeaInput')).toHaveValue('Neue Idee: bewegter Mittelteil, kontrastierende Begleitung.');
  await page.locator('#compositionHistoryButton').click();
  await expect(page.locator('#compositionHistoryDialog')).toHaveJSProperty('open',true);
  await expect(page.locator('#compositionHistoryList')).toContainText('noch keine gespeicherte Kompositionsfassung');
  const provenance = await page.evaluate(() => {
    const source={slot:1,name:'Quelle',score:{ti:'Quelle',bpm:90,ts:{n:4,d:4},k:'Am',sm:'ALTE SYNTHESEBEHAUPTUNG',tr:[{nm:'Piano',ch:0,pg:0,nt:[[0,1,60,80,0,1]],ct:[]}]}};
    const fresh={ti:'Neu',bpm:90,ts:{n:4,d:4},k:'Am',sm:'ALTE SYNTHESEBEHAUPTUNG',tr:[{nm:'Piano',ch:0,pg:0,nt:[[0,1,64,80,0,1]],ct:[]}]};
    const withSummary=window.MCLSessionV139.materializeAction({type:'new_score',summary:'Aktuelle Fassung',score:fresh},[source],'');
    const withoutSummary=window.MCLSessionV139.materializeAction({type:'new_score',score:fresh},[source],'');
    return {a:withSummary.sm,b:withoutSummary.sm};
  });
  expect(provenance).toEqual({a:'Aktuelle Fassung',b:'Neu komponierte MIDI-Fassung.'});
  const validation = await page.evaluate(() => {
    const good={ti:'Frei',bpm:66,ts:{n:6,d:8},k:'e-Moll',tr:[{nm:'Piano',nt:[[0,1,60,80,0,1],[1,1,64,72,0,1]]}]};
    const different={ti:'Frei',bpm:120,ts:{n:3,d:4},k:'Des-Dur',tr:[{nm:'Piano',nt:[[0,1,61,80,0,1],[1,2,68,90,0,1]]}]};
    const badPitch={ti:'Defekt',bpm:66,ts:{n:4,d:4},tr:[{nm:'Piano',nt:[[0,1,200,80,0,1]]}]};
    const badDuration={ti:'Defekt',bpm:66,ts:{n:4,d:4},tr:[{nm:'Piano',nt:[[0,0,60,80,0,1]]}]};
    return {good:window.MCLSessionV139.scoreIssues(good),different:window.MCLSessionV139.scoreIssues(different),badPitch:window.MCLSessionV139.scoreIssues(badPitch),badDuration:window.MCLSessionV139.scoreIssues(badDuration)};
  });
  expect(validation.good).toEqual([]);
  expect(validation.different).toEqual([]);
  expect(validation.badPitch.some(x=>x.includes('ungültige Note'))).toBeTruthy();
  expect(validation.badDuration.some(x=>x.includes('ungültige Note'))).toBeTruthy();
  const traceSafety=await page.evaluate(()=>{
    const id=window.MCLAiTrace.request('test','https://example.test/api?key=secret',{headers:{Authorization:'Bearer secret','x-api-key':'secret','Content-Type':'application/json'}},{model:'test',messages:[{role:'user',content:'vollständiger Auftrag'}]});
    window.MCLAiTrace.response(id,{status:200,statusText:'OK',headers:new Headers({'content-type':'application/json'})},'{"answer":"vollständige Antwort"}');
    return window.MCLAiTrace.snapshot().at(-1);
  });
  expect(traceSafety.url).not.toContain('secret');
  expect(traceSafety.headers.authorization).toBe('[REDACTED]');
  expect(traceSafety.headers['x-api-key']).toBe('[REDACTED]');
  expect(JSON.stringify(traceSafety.body)).toContain('vollständiger Auftrag');
  expect(traceSafety.rawResponse).toContain('vollständige Antwort');
  expect(errors).toEqual([]);
});
