(()=>{
'use strict';
if(window.MCLActionDomain)return;
const clone=x=>x==null?x:JSON.parse(JSON.stringify(x));
const isScore=x=>!!x&&Array.isArray(x.tr)&&x.tr.some(t=>Array.isArray(t?.nt));
const validTrack=t=>!!t&&typeof t==='object'&&Array.isArray(t.nt);
function trackIndex(score,op){if(Number.isInteger(op?.index))return op.index;if(typeof op?.name==='string'){const hits=(score.tr||[]).map((t,i)=>t?.nm===op.name?i:-1).filter(i=>i>=0);if(hits.length===1)return hits[0]}return-1}
const sortEvents=a=>(a||[]).slice().sort((x,y)=>(Number(x?.[0])||0)-(Number(y?.[0])||0));
function applyPatch(action,sources){const src=sources.find(x=>Number(x.slot)===Number(action?.baseSlot));if(!src||!isScore(src.score)||!Array.isArray(action?.ops))return null;const score=clone(src.score);if(String(action.title||'').trim())score.ti=action.title.trim();if(String(action.summary||'').trim())score.sm=action.summary.trim();if(action.meta&&typeof action.meta==='object')for(const k of['bpm','ts','k'])if(Object.prototype.hasOwnProperty.call(action.meta,k))score[k]=clone(action.meta[k]);for(const op of action.ops){if(!op||typeof op.op!=='string')return null;if(op.op==='add_track'){if(!validTrack(op.track))return null;score.tr.push(clone(op.track));continue}if(op.op==='insert_track'){if(!validTrack(op.track))return null;const at=Math.max(0,Math.min(score.tr.length,Math.trunc(Number(op.index)||0)));score.tr.splice(at,0,clone(op.track));continue}const ix=trackIndex(score,op);if(ix<0||ix>=score.tr.length)return null;if(op.op==='replace_track'){if(!validTrack(op.track))return null;score.tr[ix]=clone(op.track);continue}if(op.op==='delete_track'){score.tr.splice(ix,1);continue}if(op.op==='replace_range'){const start=Number(op.start),end=Number(op.end);if(!Number.isFinite(start)||!Number.isFinite(end)||end<=start||!Array.isArray(op.nt))return null;const tr=clone(score.tr[ix]);tr.nt=sortEvents((tr.nt||[]).filter(n=>{const t=Number(n?.[0]);return!(Number.isFinite(t)&&t>=start&&t<end)}).concat(clone(op.nt)));if(Array.isArray(op.ct))tr.ct=sortEvents((tr.ct||[]).filter(c=>{const t=Number(c?.[0]);return!(Number.isFinite(t)&&t>=start&&t<end)}).concat(clone(op.ct)));score.tr[ix]=tr;continue}return null}return isScore(score)?score:null}
function trackSignature(t){try{return JSON.stringify({nm:t?.nm||'',ch:t?.ch??null,pg:t?.pg??null,nt:t?.nt||[],ct:t?.ct||[]})}catch{return''}}
function mergeAction(action,sources){if(!Array.isArray(action?.sources)||!action.sources.length)return null;let score=null;const tracks=[],seen=new Set();for(const spec of action.sources){const src=sources.find(x=>Number(x.slot)===Number(spec?.slot));if(!src||!isScore(src.score))return null;if(!score)score=clone(src.score);let chosen=src.score.tr||[];if(Array.isArray(spec.tracks)&&spec.tracks.length){const names=new Set(spec.tracks.map(String));chosen=chosen.filter(t=>names.has(String(t?.nm||'')));if(chosen.length!==names.size)return null}for(const t of chosen){const sig=trackSignature(t);if(seen.has(sig))continue;tracks.push(clone(t));seen.add(sig)}}if(!score||!tracks.length)return null;score.tr=tracks;if(String(action.title||'').trim())score.ti=action.title.trim();else if(!String(score.ti||'').trim())score.ti='Gemeinsame Fassung';score.sm=String(action.summary||'').trim()||'Vorhandene Spuren wurden lokal zusammengeführt.';return score}
function materialize(action,sources=[]){if(!action||action.invalid||action.__invalid)return null;const type=String(action.type||'').toLowerCase();let score=null;if(type==='patch')score=applyPatch(action,sources);else if(type==='merge')score=mergeAction(action,sources);else if((type==='new_score'||type==='replace_score')&&isScore(action.score))score=clone(action.score);if(!isScore(score))return null;if(!String(score.ti||'').trim())score.ti=String(action.title||'Neue Komposition').trim()||'Neue Komposition';if(String(action.summary||'').trim()&&!String(score.sm||'').trim())score.sm=action.summary.trim();return score}
window.MCLActionDomain={version:'1.0.0',materialize,isScore};
})();