(()=>{'use strict';

const ENGINE_NAME='Composition Engine';
const ENGINE_VERSION='1.1.2';

const TECHNICAL_CONTRACT=`TECHNISCHE AUSGABEANFORDERUNG – KEINE MUSIKALISCHEN ZUSATZREGELN:\nAntworte ausschließlich mit validem JSON, ohne Markdown und ohne Text außerhalb des JSON.\nDie Partitur steht entweder direkt im Wurzelobjekt oder im Feld "score".\nPartiturformat:\n{\n  "title": "optional",\n  "bpm": Zahl,\n  "timeSignature": [Zaehler, Nenner],\n  "tracks": [\n    {\n      "name": "Instrument",\n      "program": 0-127,\n      "channel": 0-15,\n      "notes": [[StartBeat, DauerInBeats, MIDIPitch, Velocity], ...]\n    }\n  ]\n}\nWeitere Textfelder, die der Benutzer in seinem Auftrag ausdrücklich verlangt, dürfen zusätzlich im JSON stehen.\nStartBeat und DauerInBeats dürfen Dezimalzahlen sein. MIDI-Pitch 0-127, Velocity 1-127.\nDas technische Format macht keinerlei Vorgaben zu Stil, Harmonik, Melodik, Rhythmik, Form, Artikulation oder musikalischer Qualität.`;
function createPrompts(snapshot,draft='',translated=''){
 return{
  musicalDraft:'Komponiere das verlangte Stück musikalisch frei und eigenständig. Konzentriere dich ausschließlich auf musikalische Gestalt, Verlauf, Stimmen, Rhythmus, Harmonik, Artikulation und Charakter. Denke noch NICHT an MIDI-Codierung, QN-Werte, CS-Zeilen oder ein technisches Ausgabeformat. Schreibe einen vollständigen, konkret ausnotierbaren musikalischen Entwurf, aus dem anschließend eine andere technische Instanz die MIDI-Daten erzeugen kann. Gib am Anfang einen kurzen passenden Werktitel als „Titel: …“ sowie, soweit musikalisch bestimmbar, „Tonart: …“ und „Tempo: …“ als musikalische Tempoangabe (z. B. Andante, Allegro moderato) an; dies soll die musikalische Gestaltung nicht einschränken. Mache keine Erläuterung über deine Arbeitsweise.\n\nAUFTRAG:\n'+snapshot.visibleTask,
  midiTranslation:'Du bist jetzt ausschließlich Notations- und MIDI-Übersetzer. Übertrage den folgenden bereits fertigen musikalischen Entwurf so vollständig und werkgetreu wie möglich in das nachfolgend geforderte technische Partiturformat. Komponiere NICHT neu, vereinfache NICHT, regularisiere NICHT den Rhythmus und ersetze keine ungewöhnlichen musikalischen Entscheidungen durch Standards. Bewahre insbesondere rhythmische Vielfalt, Pausen, Stimmführung und Phrasierung des Entwurfs.\n\nURSPRÜNGLICHER AUFTRAG:\n'+snapshot.visibleTask+'\n\nFERTIGER MUSIKALISCHER ENTWURF:\n'+draft+'\n\n'+TECHNICAL_CONTRACT,
  compositionIdea:'Analysiere die soeben entstandene Komposition und formuliere ihre Kompositionsbeschreibung knapp und musikalisch konkret. Nenne keine technischen Metadatenzeilen; diese erzeugt die Engine selbst. Beschreibe in wenigen Sätzen Charakter, formalen Verlauf, rhythmische und harmonische Grundidee sowie das Verhältnis der Stimmen bzw. Instrumente. Erfinde nichts und gib keine Bewertung ab. Antworte nur mit der musikalischen Beschreibung als normalem Text.\n\nURSPRÜNGLICHER AUFTRAG:\n'+snapshot.visibleTask+'\n\nMUSIKALISCHER ENTWURF:\n'+draft
 };
}
function duplicateTitlePrompt(title,allTitles,draft){return'Erfinde ausschließlich einen neuen kurzen Werktitel für die bereits fertige Komposition. Der Titel darf keinen der bereits verwendeten Titel wiederholen und soll zur Komposition passen. Ändere keinerlei musikalischen Inhalt. Antworte ausschließlich mit dem neuen Titel, ohne Anführungszeichen, Präfix oder Erläuterung.\n\nBISHERIGER TITEL:\n'+title+'\n\nBEREITS VERWENDETE TITEL:\n'+allTitles.join('\n')+'\n\nMUSIKALISCHER ENTWURF:\n'+draft}
function makeRequest(p,m,promptText,stage){if(p==='openai')return{provider:p,model:m,url:'https://api.openai.com/v1/responses',method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer {{API_KEY}}'},body:{model:m,input:[{role:'user',content:[{type:'input_text',text:promptText}]}],store:false}};if(p==='anthropic'){const body={model:m,max_tokens:32768,messages:[{role:'user',content:promptText}]};if(/^claude-(?:sonnet|opus)-5(?:$|-)/i.test(m)&&stage==='midi_translation'){body.thinking={type:'disabled'};body.max_tokens=32768}return{provider:p,model:m,url:'https://api.anthropic.com/v1/messages',method:'POST',headers:{'Content-Type':'application/json','x-api-key':'{{API_KEY}}','anthropic-version':'2023-06-01','anthropic-dangerous-direct-browser-access':'true'},body};}return{provider:p,model:m,url:`https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(m)}:generateContent?key={{API_KEY}}`,method:'POST',headers:{'Content-Type':'application/json'},body:{contents:[{role:'user',parts:[{text:promptText}]}]}}}
function actualRequest(s,key){const headers={...s.headers};let url=s.url;for(const k of Object.keys(headers)){if(typeof headers[k]==='string'&&headers[k].includes('{{API_KEY}}'))headers[k]=headers[k].replace('{{API_KEY}}',key)}url=url.replace('{{API_KEY}}',encodeURIComponent(key));return{url,headers,body:structuredClone(s.body)}}
function extractText(p,j){if(p==='openai'){if(typeof j.output_text==='string')return j.output_text;const parts=[];for(const item of(j.output||[]))for(const c of(item.content||[]))if(typeof c.text==='string')parts.push(c.text);return parts.join('\n')}if(p==='anthropic')return(j.content||[]).filter(x=>x.type==='text').map(x=>x.text||'').join('\n');return(j.candidates||[]).flatMap(c=>c.content?.parts||[]).map(p=>p.text||'').join('\n')}
function extractJson(text){let s=String(text||'').trim().replace(/^\`\`\`(?:json)?\s*/i,'').replace(/\s*\`\`\`$/,'').trim();try{return JSON.parse(s)}catch(_){const a=s.indexOf('{'),b=s.lastIndexOf('}');if(a>=0&&b>a)return JSON.parse(s.slice(a,b+1));throw _}}
function findScore(o){const s=o&&o.score&&Array.isArray(o.score.tracks)?o.score:o;if(!s||!Array.isArray(s.tracks)||!Number.isFinite(Number(s.bpm)))throw new Error('Kein gültiges Partitur-Objekt mit bpm und tracks gefunden.');return s}
function findIdea(o){if(!o||typeof o!=='object')return'';for(const k of['idea','kompositionsidee','description','beschreibung','concept'])if(typeof o[k]==='string'&&o[k].trim())return o[k].trim();return''}
async function sha256Text(text){const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(text));return[...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')}
async function sha256Buffer(buf){const b=await crypto.subtle.digest('SHA-256',buf);return[...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')}
function vlq(n){n=Math.max(0,Math.round(n));let b=[n&127];while((n>>=7))b.unshift((n&127)|128);return b}const strBytes=s=>[...new TextEncoder().encode(s)],u32=n=>[(n>>>24)&255,(n>>>16)&255,(n>>>8)&255,n&255],u16=n=>[(n>>>8)&255,n&255],chunk=(t,d)=>[...strBytes(t),...u32(d.length),...d];
function buildMidi(score){const ppq=480,bpm=Math.max(20,Math.min(400,Number(score.bpm)||120)),ts=Array.isArray(score.timeSignature)?score.timeSignature:[4,4],tracks=[],meta=[];const mpqn=Math.round(60000000/bpm);meta.push({tick:0,bytes:[255,81,3,(mpqn>>16)&255,(mpqn>>8)&255,mpqn&255]},{tick:0,bytes:[255,88,4,Number(ts[0])||4,Math.max(0,Math.round(Math.log2(Number(ts[1])||4))),24,8]});let last=0,md=[];for(const e of meta){md.push(...vlq(e.tick-last),...e.bytes);last=e.tick}md.push(0,255,47,0);tracks.push(chunk('MTrk',md));(score.tracks||[]).forEach((tr,ti)=>{const ch=Math.max(0,Math.min(15,Number.isFinite(Number(tr.channel))?Number(tr.channel):ti%16)),prog=Math.max(0,Math.min(127,Number(tr.program)||0)),ev=[];const name=strBytes(String(tr.name||`Track ${ti+1}`));ev.push({tick:0,p:0,b:[255,3,...vlq(name.length),...name]},{tick:0,p:1,b:[192|ch,prog]});for(const n of(tr.notes||[])){if(!Array.isArray(n)||n.length<4)continue;const st=Math.max(0,Number(n[0])||0),du=Math.max(.01,Number(n[1])||.25),pitch=Math.max(0,Math.min(127,Math.round(Number(n[2])||60))),vel=Math.max(1,Math.min(127,Math.round(Number(n[3])||80)));ev.push({tick:Math.round(st*ppq),p:2,b:[144|ch,pitch,vel]},{tick:Math.round((st+du)*ppq),p:1,b:[128|ch,pitch,0]})}ev.sort((a,b)=>a.tick-b.tick||a.p-b.p);let prev=0,d=[];for(const e of ev){d.push(...vlq(e.tick-prev),...e.b);prev=e.tick}d.push(0,255,47,0);tracks.push(chunk('MTrk',d))});return new Uint8Array([...chunk('MThd',[...u16(1),...u16(tracks.length),...u16(ppq)]),...tracks.flat()])}

function draftField(draft,label){const lines=String(draft||'').split(/\r?\n/);const prefix=String(label||'').toLowerCase()+':';for(const line of lines){const t=line.trim();if(t.toLowerCase().startsWith(prefix))return t.slice(prefix.length).trim()}return''}
function scoreBarCount(score){const ts=Array.isArray(score?.timeSignature)?score.timeSignature:[4,4],beats=(Number(ts[0])||4)*(4/(Number(ts[1])||4));let end=0;for(const tr of(score?.tracks||[]))for(const n of(tr.notes||[]))if(Array.isArray(n))end=Math.max(end,(Number(n[0])||0)+(Number(n[1])||0));return Math.max(1,Math.ceil(end/Math.max(.25,beats)))}
function providerName(p){return p==='anthropic'?'Anthropic / Claude':p==='google'?'Google / Gemini':p==='openai'?'OpenAI':String(p||'')}
function compositionProfile(snapshot,score,draft,description){const bpm=Number(score?.bpm)||null,key=String(score?.key||score?.keySignature||score?.tonality||draftField(draft,'Tonart')||'').trim(),tempo=String(score?.tempo||score?.tempoMarking||draftField(draft,'Tempo')||'').trim(),bars=scoreBarCount(score),provider=providerName(snapshot?.provider),model=String(snapshot?.model||'').trim();const fields=[bpm?bpm+' BPM':'',tempo,key,bars+' Takte',[provider,model].filter(Boolean).join(' · ')].filter(Boolean);return{bpm,tempo,key,barCount:bars,provider,model,description:String(description||'').trim(),text:fields.join(' · ')+'\n\n'+String(description||'').trim()}}
async function compose({snapshot,key,repeatOf=null,seriesId=null,runId,now,requestModel,usedTitles=[]}){
 const startedAt=now(),run={id:runId,testId:runId,schema:'minimal-composer-diagnosis-v3',app:{name:'Minimal Composer Modular',version:'0.5.5'},seriesId,startedAt,repeatOf,contextMode:'isolated-three-stage',input:{visibleTask:snapshot.visibleTask,provider:snapshot.provider,model:snapshot.model},technicalContract:TECHNICAL_CONTRACT,events:[],aiCalls:[],requestSnapshot:structuredClone(snapshot)};
 const ev=(phase,data={})=>run.events.push({at:now(),phase,...data});
 ev('run_started',{note:'Keine frühere Unterhaltung oder Komposition wird an das Modell übertragen.'});
 const call=async(prompt,stage)=>requestModel({snapshot,key,promptText:prompt,stage,run,event:ev});
 const draft=await call(createPrompts(snapshot).musicalDraft,'musical_draft');if(!draft.trim())throw new Error('Der musikalische Entwurf ist leer.');run.musicalDraft=draft;
 const translated=await call(createPrompts(snapshot,draft).midiTranslation,'midi_translation');const obj=extractJson(translated);run.parsedModelJson=obj;ev('model_json_parsed',{stage:'midi_translation',changed:false,note:'Nur JSON geparst; keine musikalische Korrektur.'});const score=findScore(obj);run.score=score;
 const title=String(score?.title||'').trim(),allTitles=usedTitles.filter(Boolean);if(title&&allTitles.some(t=>String(t).toLocaleLowerCase('de-DE')===title.toLocaleLowerCase('de-DE'))){let nt=(await call(duplicateTitlePrompt(title,allTitles,draft),'title_renaming')).trim().replace(/^Titel:\s*/i,'').replace(/^['“”"]|['“”"]$/g,'').trim();if(!nt||allTitles.some(t=>String(t).toLocaleLowerCase('de-DE')===nt.toLocaleLowerCase('de-DE')))nt=title+' '+new Date().toLocaleDateString('de-DE');score.title=nt;ev('duplicate_title_replaced',{oldTitle:title,newTitle:nt})}
 const midiBytes=buildMidi(score),buf=midiBytes.buffer.slice(midiBytes.byteOffset,midiBytes.byteOffset+midiBytes.byteLength),midiHash=await sha256Buffer(buf);run.midi={bytes:midiBytes.byteLength,sha256:midiHash,note:'Deterministisch lokal aus den unveränderten Partiturwerten erzeugt; keine musikalische Nachbearbeitung.'};ev('midi_generated',{bytes:midiBytes.byteLength,sha256:midiHash});
 const idea=await call(createPrompts(snapshot,draft,translated).compositionIdea,'composition_idea_afterwards');run.idea=idea.trim();run.profile=compositionProfile(snapshot,score,draft,run.idea);ev('composition_profile_created',{bpm:run.profile.bpm,tempo:run.profile.tempo,key:run.profile.key,barCount:run.profile.barCount,provider:run.profile.provider,model:run.profile.model});run.completedAt=now();run.status='ok';
 return{run,midiBytes};
}

window.CompositionEngine=Object.freeze({name:ENGINE_NAME,version:ENGINE_VERSION,compose,TECHNICAL_CONTRACT,createPrompts,duplicateTitlePrompt,makeRequest,actualRequest,extractText,extractJson,findScore,findIdea,sha256Text,sha256Buffer,buildMidi});
})();
