(()=>{
'use strict';
if(window.__mclExplicitModeV200)return;
window.__mclExplicitModeV200=true;
const VERSION='2.0.2';
let forwardingCompose=false;
window.MCLRequestMode=window.MCLRequestMode==='compose'?'compose':'chat';
function setMode(mode){window.MCLRequestMode=mode==='compose'?'compose':'chat'}
function currentIdea(){return String(window.MCLCompositionIdea?.get?.()||document.getElementById('compositionIdeaInput')?.value||'').trim()}
function setIdea(text){const value=String(text||'').trim();if(!value)return;if(window.MCLCompositionIdea?.set)window.MCLCompositionIdea.set(value,{generated:true,source:'chat'});else{const e=document.getElementById('compositionIdeaInput');if(e)e.value=value}}
function removeLegacyProposalMarkers(){const key='music-chat-lab.chats.v1';try{const chats=JSON.parse(localStorage.getItem(key)||'[]');if(!Array.isArray(chats))return;let changed=false;for(const chat of chats){if(!Array.isArray(chat?.messages))continue;for(const message of chat.messages){if(typeof message?.text!=='string')continue;const cleaned=message.text.replace(/\n*\[MCL-(?:OPENAI-)?VORSCHLAG:[a-z0-9]+\]\s*/ig,'\n').replace(/\n{3,}/g,'\n\n').trim();if(cleaned!==message.text){message.text=cleaned;changed=true}}}if(changed)localStorage.setItem(key,JSON.stringify(chats))}catch(_){}}
function hasAssistantContext(){try{const chats=JSON.parse(localStorage.getItem('music-chat-lab.chats.v1')||'[]'),id=localStorage.getItem('music-chat-lab.active-chat.v1'),chat=Array.isArray(chats)?chats.find(c=>c?.id===id):null;return!!chat?.messages?.some(m=>m?.role==='assistant'&&!m?.isError&&!m?.thinking&&String(m?.text||'').trim())}catch{return false}}
function applyParsed(parsed){if(parsed?.concept)setIdea(parsed.concept);return parsed}
function bindButtons(){const chat=document.getElementById('sendButton'),compose=document.getElementById('composeButton'),input=document.getElementById('messageInput');if(!chat||!compose||!input)return;chat.addEventListener('click',()=>{if(!forwardingCompose)setMode('chat')},true);compose.addEventListener('click',()=>{if(chat.disabled)return;if(!input.value.trim()){if(currentIdea())input.value='Komponiere eine neue Fassung auf Grundlage der aktuellen Kompositionsidee.';else if(hasAssistantContext())input.value='Setze den zuletzt im Chat entwickelten Kompositionsvorschlag jetzt als MIDI um.';else{const note=document.getElementById('composerNote');if(note)note.textContent='Bitte zuerst einen Kompositionsauftrag eingeben oder eine Kompositionsidee formulieren.';return}input.dispatchEvent(new Event('input',{bubbles:true}))}setMode('compose');forwardingCompose=true;try{chat.click()}finally{forwardingCompose=false}});input.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey)setMode('chat')},true);const syncDisabled=()=>{compose.disabled=chat.disabled};syncDisabled();new MutationObserver(syncDisabled).observe(chat,{attributes:true,attributeFilter:['disabled']})}
removeLegacyProposalMarkers();bindButtons();window.MCLExplicitModeV200={version:VERSION,getMode:()=>window.MCLRequestMode,setMode,currentIdea,setIdea,applyParsed};
})();