(()=>{
'use strict';
if(window.MCLRequestRuntime)return;
let activeController=null,last=null;
const clone=x=>x==null?x:JSON.parse(JSON.stringify(x));
function safeSpec(spec){return{provider:spec?.provider||null,model:spec?.model||null,mode:spec?.mode||null,turnId:spec?.turnId||null,messageCount:Array.isArray(spec?.messages)?spec.messages.length:0,systemChars:String(spec?.system||'').length};}
function abort(reason='Laufende Anfrage abgebrochen.'){if(activeController){try{activeController.abort()}catch{}activeController=null}const note=document.getElementById('composerNote');if(note&&reason)note.textContent=reason}
async function run(spec){if(!window.MCLSessionRequest||!window.MCLProviderPolicy||!window.MCLProviderGateway)throw new Error('Request-Runtime ist nicht vollständig geladen.');abort('');const controller=new AbortController();activeController=controller;const policy=window.MCLProviderPolicy.forRequest(spec.provider,spec.model,{mode:spec.mode});const req=window.MCLSessionRequest.build({...spec,...policy});last={startedAt:new Date().toISOString(),request:safeSpec(spec),policy:clone(policy),status:'running'};try{const result=await window.MCLProviderGateway.request({...req,apiKey:spec.apiKey,signal:controller.signal});const parsed=window.MCLSessionRequest.parseMachineBlocks(result.text),usageRecord={provider:result.provider,model:result.model,usage:result.usage,turnId:spec.turnId||window.MCLUsageActiveTurn?.()||null};if(window.MCLUsageRecord)window.MCLUsageRecord(usageRecord);else window.MCLProviderUsage?.record?.(usageRecord);window.MCLExplicitModeV200?.applyParsed?.(parsed);if(parsed.memory)window.MCLSessionCore?.saveMemory?.(parsed.memory);last={...last,finishedAt:new Date().toISOString(),status:'success',response:{provider:result.provider,model:result.model,text:String(result.text||''),usage:clone(result.usage||null)},parsed:{visible:String(parsed.visible||''),action:clone(parsed.action||null),need:clone(parsed.need||null),memory:parsed.memory||null,concept:parsed.concept||null}};return{...result,...parsed}}catch(error){last={...last,finishedAt:new Date().toISOString(),status:'error',error:{name:error?.name||'Error',message:error?.message||String(error)}};throw error}finally{if(activeController===controller)activeController=null}}
window.MCLRequestRuntime={version:'2.1.0',run,abort,get active(){return!!activeController},lastDiagnostic:()=>clone(last)};
})();
