(()=>{
'use strict';
if(window.MCLSessionCore)return;
const MEMORY_KEY='music-chat-lab.session-memory.v3';
const ACTIVE_CHAT_KEY='music-chat-lab.active-chat.v1';
const RECENT_MESSAGES=8,MAX_MEMORY_CHARS=900,MAX_LEGACY_CONTEXT_CHARS=4200,MAX_SCORE_REQUESTS=3;
const clone=x=>x==null?x:JSON.parse(JSON.stringify(x));
const SCORE_RE=/\[MCL-ENGINE14-SCORE name=("(?:[^"\\]|\\.)*")\]\n[\s\S]*?\n\[\/MCL-ENGINE14-SCORE\]/g;
const LEGACY_BLOCKS=[/\n*--- MUSIKALISCHER ARBEITSTISCH(?: \(KATALOG\))? ---[\s\S]*?--- ENDE MUSIKALISCHER ARBEITSTISCH(?: \(KATALOG\))? ---\n*/g,/\n*--- AUSGEWÄHLTES MUSIKMATERIAL ---[\s\S]*?--- ENDE AUSGEWÄHLTES MUSIKMATERIAL ---\n*/g,/\n*--- AUTOMATISCH BEREITGESTELLTES MUSIKMATERIAL ---[\s\S]*?--- ENDE AUTOMATISCH BEREITGESTELLTES MUSIKMATERIAL ---\n*/g];
const INTERNAL_RE=/\n*\[MCL-(?:DIALOG-OFFER-ACCEPTED|FORTSETZUNG-V123|AKTUELLER-GEGENSTAND-V124|DIALOGKONTEXT-V126)\][\s\S]*$/i;
function cleanLegacy(text){let s=String(text||'');s=s.replace(SCORE_RE,'');SCORE_RE.lastIndex=0;for(const re of LEGACY_BLOCKS)s=s.replace(re,'\n');return s.replace(INTERNAL_RE,'').replace(/\n*\[MCL-(?:OPENAI-)?VORSCHLAG:[a-z0-9]+\]\s*/ig,'\n').replace(/\n{3,}/g,'\n\n').trim()}
function normalizeMessages(messages){return(Array.isArray(messages)?messages:[]).filter(m=>m&&(m.role==='user'||m.role==='assistant')).map(m=>({role:m.role,text:cleanLegacy(m.text)})).filter(m=>m.text)}
function readMemory(){try{const all=JSON.parse(localStorage.getItem(MEMORY_KEY)||'{}')||{};return{all,id:localStorage.getItem(ACTIVE_CHAT_KEY)||'default'}}catch{return{all:{},id:'default'}}}
function getMemory(){const x=readMemory();return String(x.all[x.id]||'').slice(0,MAX_MEMORY_CHARS)}
function saveMemory(text){const mem=String(text||'').replace(/\s+/g,' ').trim().slice(0,MAX_MEMORY_CHARS);if(!mem)return;try{const x=readMemory();x.all[x.id]=mem;localStorage.setItem(MEMORY_KEY,JSON.stringify(x.all))}catch{}}
function compactOld(msgs){if(msgs.length<=RECENT_MESSAGES)return'';const parts=[];let chars=0;for(const m of msgs.slice(0,-RECENT_MESSAGES)){let t=m.text.replace(/\s+/g,' ').trim();if(t.length>520)t=t.slice(0,340)+' … '+t.slice(-140);const line=`${m.role==='user'?'Nutzer':'KI'}: ${t}`;if(chars+line.length>MAX_LEGACY_CONTEXT_CHARS)break;parts.push(line);chars+=line.length+1}return parts.join('\n')}
function compressMessages(msgs,memory){const keep=(msgs.length<=RECENT_MESSAGES||!memory)?Math.max(RECENT_MESSAGES,12):RECENT_MESSAGES;let start=Math.max(0,msgs.length-keep);if(start>0&&msgs[start]?.role==='assistant')start--;const out=msgs.slice(start);while(out.length&&out[0].role==='assistant')out.shift();return out}
function workspaceSources(){try{return(window.MCLMidiWorkspaceSources?.()||window.MCLMidiSlots?.all?.()||[]).filter(x=>x?.score?.tr?.length).map(x=>({slot:Number(x.slot),name:x.name||x.score?.ti||`Stück ${x.slot}`,kind:x.kind||'',score:clone(x.score)}))}catch{return[]}}
function activeSlot(){try{const b=document.querySelector('.mcl-midi-slot.active');return b?Number(b.dataset.slot)+1:null}catch{return null}}
function scoreInfo(x){const s=x.score||{},tr=Array.isArray(s.tr)?s.tr:[],ts=s.ts||{};let notes=0,end=0;tr.forEach(t=>(t.nt||[]).forEach(n=>{if(!Array.isArray(n))return;notes++;end=Math.max(end,(Number(n[0])||0)+(Number(n[1])||0))}));const n=Number(ts.n)||null,d=Number(ts.d)||null,bar=n&&d?n*(4/d):null;return{slot:x.slot,name:x.name,kind:x.kind,tracks:tr.map(t=>t.nm||'Spur').join(', '),notes,bars:bar?Number((end/bar).toFixed(2)):null,beats:Number(end.toFixed(2)),bpm:s.bpm??null,meter:n&&d?`${n}/${d}`:null,key:s.k||null}}
function catalogue(sources,active){if(!sources.length)return'Keine MIDI-Fassung im Arbeitstisch.';return sources.map(x=>{const i=scoreInfo(x);return `Speicher ${i.slot}${i.slot===active?' [AKTIV]':''}: ${i.name} | Spuren: ${i.tracks||'?'} | ${i.notes} Noten | ${i.bars??'?'} Takte | ${i.bpm??'?'} BPM | ${i.meter??'?'} | ${i.key??'Tonart offen'}`}).join('\n')}
function scoreBlocks(selected){return selected.map(x=>`<MCL_SCORE slot="${x.slot}" name=${JSON.stringify(x.name)}>\n${JSON.stringify(x.score)}\n</MCL_SCORE>`).join('\n\n')}
function sourcesForSlots(slots,sources){const out=[];for(const n of slots||[]){const src=sources.find(x=>Number(x.slot)===Number(n));if(src&&!out.includes(src))out.push(src)}return out.slice(0,MAX_SCORE_REQUESTS)}
function withScores(msgs,user,selected){const out=msgs.map(x=>({...x}));for(let i=out.length-1;i>=0;i--){if(out[i].role!=='user')continue;out[i].text=`${cleanLegacy(user)}${selected.length?`\n\n${scoreBlocks(selected)}`:''}`.trim();break}return out}
function systemPrompt(memory,legacy,catalogueText,active,provided){const providedLine=provided.length?`Für diesen Zug sind die vollständigen Notendaten von Speicher ${provided.map(x=>x.slot).join(', ')} beigefügt.`:'Für diesen Zug sind zunächst keine vollständigen Notendaten beigefügt.';return `Du bist Music Chat Lab, ein zusammenhängender Musik-Chat mit direkter MIDI-Handlungsfähigkeit. Behandle den Dialog als fortlaufendes Gespräch.\n\nMUSIKALISCHER ARBEITSTISCH (KATALOG):\n${catalogueText}\nAktiver Speicher: ${active??'keiner'}.\n${providedLine}\n\nNOTENDATEN BEI BEDARF: Wenn du vollständige Notendaten brauchst und sie noch nicht als <MCL_SCORE> beigefügt sind, antworte ausschließlich mit <MCL_NEED>{"slots":[1,3]}</MCL_NEED>. Maximal ${MAX_SCORE_REQUESTS} Speicher.\n\nMIDI-AKTIONEN: Nutze <MCL_ACTION> nur für tatsächliche MIDI-Erzeugung oder Bearbeitung. PATCH verändert vorhandenes Material teilweise, MERGE führt vorhandene Spuren technisch zusammen, NEW_SCORE erzeugt vollständig neue Musik, REPLACE_SCORE schreibt einen vorhandenen Score als Ganzes neu. Notenformat nt=[StartBeat,Dauer,Pitch,Velocity,Staff,Gate], Controller ct=[Beat,CC,Wert].\n\nGEDÄCHTNIS: Hänge an jede normale endgültige Antwort ein kurzes <MCL_MEMORY>...</MCL_MEMORY> an, maximal ${MAX_MEMORY_CHARS} Zeichen. Bewahre nur dauerhaften Gesprächskontext, keine vollständigen Notenlisten.\n\nBISHERIGES KOMPAKTGEDÄCHTNIS:\n${memory||'(noch keines)'}${legacy?`\n\nÄLTERER DIALOGAUSZUG:\n${legacy}`:''}`}
function directive(mode,idea){if(mode==='compose'){const brief=idea?`\n\nAKTUELLE KOMPOSITIONSIDEE:\n${idea}`:'';return`AKTUELLER AUSFÜHRUNGSMODUS: KOMPONIERE. Der Nutzer hat die musikalische Ausführung ausdrücklich gewählt.${brief}\nErzeuge oder bearbeite die gewünschte MIDI-Fassung jetzt. Falls vollständige Notendaten fehlen, fordere sie mit <MCL_NEED> an. Die endgültige Antwort muss genau eine gültige <MCL_ACTION> enthalten. Musikalische Entscheidungen triffst du selbst; zusätzliche Detailvorgaben sind nicht erforderlich.`}return`AKTUELLER AUSFÜHRUNGSMODUS: CHAT. In diesem Zug wird keine MIDI-Fassung erzeugt oder verändert und es darf keine <MCL_ACTION> ausgegeben werden. Wenn im Gespräch eine konkrete anschließend ausführbare Kompositions- oder Bearbeitungsidee entsteht oder verändert wird, hänge <MCL_CONCEPT>die aktuelle kurze Idee</MCL_CONCEPT> an.`}
function buildTurn({messages,mode='chat',idea='',providedSlots=[]}={}){const normalized=normalizeMessages(messages),memory=getMemory(),legacy=compactOld(normalized),sources=workspaceSources(),active=activeSlot(),provided=sourcesForSlots(providedSlots,sources),user=[...normalized].reverse().find(m=>m.role==='user')?.text||'',compressed=compressMessages(normalized,memory),finalMessages=withScores(compressed,user,provided),system=`${directive(mode,idea)}\n\n${systemPrompt(memory,legacy,catalogue(sources,active),active,provided)}`;return{messages:finalMessages,system,sources,active,provided,memory,user}}
window.MCLSessionCore={version:'0.1.0',cleanLegacy,normalizeMessages,getMemory,saveMemory,workspaceSources,sourcesForSlots,buildTurn};
})();